# 服务器配置
server:
  port: 8888

# 日志配置
logger:
  level: DEBUG #开发环境需:DEBUG ; 生产环境：INFO
  style: console  # console / json
  #path: /Users/tao/Documents/temp/hotsearch.log

kubernetes:
   kubeconfig: ""

