# 服务器配置
server:
  port: 8080

# 日志配置
logger:
  level: DEBUG #开发环境需:DEBUG ; 生产环境：INFO
  style: console  # console / json
  #path: /Users/tao/Documents/temp/hotsearch.log

kubernetes:
   kubeconfig: ""
   clusterID: "test"
   clusterName: "测试集群"
   clusterRegionID: "default"

redis:
  addr: "172.25.83.166:6379"
  password: ""
  database: 3
  keyPrefix: "cmdb-k8s-"
